/**
 * Generates supabase/seed.sql from lib/mock-data.ts so the seeded database
 * matches the in-app demo cohort exactly. Run:
 *
 *   npx tsx scripts/gen-seed.ts > supabase/seed.sql
 *
 * Uses fixed UUIDs for the centre, teacher, and students so re-running is
 * idempotent (ON CONFLICT DO NOTHING). Child rows use generated UUIDs and are
 * cleared first so re-seeding doesn't duplicate them.
 */
import { STUDENTS } from "../lib/mock-data";

const CENTER_ID = "11111111-1111-1111-1111-111111111111";
const TEACHER_ID = "22222222-2222-2222-2222-222222222222";
const studentUuid = (i: number) =>
  `33333333-3333-3333-3333-${String(i + 1).padStart(12, "0")}`;

/** SQL-escape a string literal (double single quotes). */
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const lines: string[] = [];
lines.push("-- IELTS Pulse — seed data (generated by scripts/gen-seed.ts).");
lines.push("-- Safe to re-run: centre/teacher/students upsert by fixed id;");
lines.push("-- child rows are deleted for these students then re-inserted.");
lines.push("");

lines.push(
  `insert into public.language_centers (id, name, slug) values\n  (${q(
    CENTER_ID
  )}, ${q("Astana English Academy")}, ${q("astana-english-academy")})\n  on conflict (id) do nothing;`
);
lines.push("");
lines.push(
  `insert into public.teachers (id, center_id, name, role) values\n  (${q(
    TEACHER_ID
  )}, ${q(CENTER_ID)}, ${q("Дана Искакова")}, ${q("director")})\n  on conflict (id) do nothing;`
);
lines.push("");

// Clear child + student rows for a clean re-seed of this fixed cohort.
const studentIds = STUDENTS.map((_, i) => q(studentUuid(i))).join(", ");
lines.push(`delete from public.students where id in (${studentIds});`);
lines.push("");

STUDENTS.forEach((s, i) => {
  const sid = studentUuid(i);
  lines.push(`-- ${s.name}`);
  lines.push(
    `insert into public.students (id, center_id, teacher_id, name, initials, email, student_group, target_band, exam_date, attendance, teacher_note) values\n  (${q(
      sid
    )}, ${q(CENTER_ID)}, ${q(TEACHER_ID)}, ${q(s.name)}, ${q(s.initials)}, ${
      s.email ? q(s.email) : "null"
    }, ${q(
      s.group
    )}, ${s.targetBand}, ${q(s.examDate)}, ${s.attendance}, ${q(s.teacherNote)});`
  );

  s.mockTests.forEach((t) => {
    lines.push(
      `insert into public.mock_tests (student_id, label, taken_on, listening, reading, writing, speaking) values\n  (${q(
        sid
      )}, ${q(t.label)}, ${q(t.date)}, ${t.listening}, ${t.reading}, ${t.writing}, ${t.speaking});`
    );
  });

  s.recommendations.forEach((r) => {
    lines.push(
      `insert into public.recommendations (student_id, skill, priority, title, detail) values\n  (${q(
        sid
      )}, ${q(r.skill)}, ${q(r.priority)}, ${q(r.title)}, ${q(r.detail)});`
    );
  });

  lines.push("");
});

process.stdout.write(lines.join("\n"));
