/**
 * Generates supabase/seed.sql from lib/mock-data.ts so the seeded database
 * matches the in-app demo cohort exactly. Run:
 *
 *   npx tsx scripts/gen-seed.ts > supabase/seed.sql
 *
 * Uses fixed UUIDs for the centre, teacher, and students so re-running is
 * idempotent (ON CONFLICT DO NOTHING). Child rows use generated UUIDs and are
 * cleared first so re-seeding doesn't duplicate them.
 */
import { STUDENTS } from "../lib/mock-data";
import { GROUP_CURRENT_LESSON, LESSONS } from "../lib/lessons-data";
import { GROUP_TEACHER, PENDING_REVIEW_SEED, TEACHERS } from "../lib/admin-data";
import { HOMEWORK_SEED } from "../lib/group-data";
import { DEMO_VOCABULARY } from "../lib/vocabulary-data";

const CENTER_ID = "11111111-1111-1111-1111-111111111111";
const TEACHER_ID = "22222222-2222-2222-2222-222222222222";
const studentUuid = (i: number) =>
  `33333333-3333-3333-3333-${String(i + 1).padStart(12, "0")}`;

/** SQL-escape a string literal (double single quotes). */
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const lines: string[] = [];
lines.push("-- IELTS Pulse — seed data (generated by scripts/gen-seed.ts).");
lines.push("-- Safe to re-run: centre/teacher/students upsert by fixed id;");
lines.push("-- child rows are deleted for these students then re-inserted.");
lines.push("");

lines.push(
  `insert into public.language_centers (id, name, slug) values\n  (${q(
    CENTER_ID
  )}, ${q("Astana English Academy")}, ${q("astana-english-academy")})\n  on conflict (id) do nothing;`
);
lines.push("");
lines.push(
  `insert into public.teachers (id, center_id, name, role) values\n  (${q(
    TEACHER_ID
  )}, ${q(CENTER_ID)}, ${q("Дана Искакова")}, ${q("director")})\n  on conflict (id) do nothing;`
);
lines.push("");

// Clear child + student rows for a clean re-seed of this fixed cohort.
const studentIds = STUDENTS.map((_, i) => q(studentUuid(i))).join(", ");
lines.push(`delete from public.students where id in (${studentIds});`);
lines.push("");

STUDENTS.forEach((s, i) => {
  const sid = studentUuid(i);
  lines.push(`-- ${s.name}`);
  lines.push(
    `insert into public.students (id, center_id, teacher_id, name, initials, email, student_group, target_band, exam_date, attendance, teacher_note) values\n  (${q(
      sid
    )}, ${q(CENTER_ID)}, ${q(TEACHER_ID)}, ${q(s.name)}, ${q(s.initials)}, ${
      s.email ? q(s.email) : "null"
    }, ${q(
      s.group
    )}, ${s.targetBand}, ${q(s.examDate)}, ${s.attendance}, ${q(s.teacherNote)});`
  );

  s.mockTests.forEach((t) => {
    lines.push(
      `insert into public.mock_tests (student_id, label, taken_on, listening, reading, writing, speaking) values\n  (${q(
        sid
      )}, ${q(t.label)}, ${q(t.date)}, ${t.listening}, ${t.reading}, ${t.writing}, ${t.speaking});`
    );
  });

  s.recommendations.forEach((r) => {
    lines.push(
      `insert into public.recommendations (student_id, skill, priority, title, detail) values\n  (${q(
        sid
      )}, ${q(r.skill)}, ${q(r.priority)}, ${q(r.title)}, ${q(r.detail)});`
    );
  });

  lines.push("");
});

// --- Course syllabus -------------------------------------------------------
// The programme is centre-wide; each group's position is a pointer on `groups`.
lines.push("-- Course syllabus (lib/lessons-data.ts)");
lines.push(
  `delete from public.lessons where center_id = ${q(CENTER_ID)};`
);
LESSONS.forEach((l) => {
  const material = l.materials[0];
  lines.push(
    `insert into public.lessons (center_id, number, title, summary, skill, material_title, material_url) values\n  (${q(
      CENTER_ID
    )}, ${l.number}, ${q(l.title)}, ${q(l.summary)}, ${q(l.skill)}, ${
      material ? q(material.title) : "null"
    }, ${material ? q(material.url) : "null"});`
  );
});
lines.push("");

lines.push("-- Where each group currently stands in the programme");
Object.entries(GROUP_CURRENT_LESSON).forEach(([group, lesson]) => {
  lines.push(
    `update public.groups set current_lesson = ${lesson} where name = ${q(group)};`
  );
});
lines.push("");

// --- Staff, group ownership and the review queue ---------------------------
lines.push("-- Teaching staff (lib/admin-data.ts)");
TEACHERS.forEach((t) => {
  lines.push(
    `insert into public.teachers (id, center_id, name, role) values\n  (${q(
      t.id
    )}, ${q(CENTER_ID)}, ${q(t.name)}, ${q(t.role)})\n  on conflict (id) do update set name = excluded.name, role = excluded.role;`
  );
});
lines.push("");

lines.push("-- Which teacher runs which group");
Object.entries(GROUP_TEACHER).forEach(([group, teacherId]) => {
  lines.push(
    `update public.groups set teacher_id = ${q(teacherId)} where name = ${q(group)};`
  );
});
lines.push("");

const hwUuid = (n: number) =>
  `55555555-5555-5555-5555-${String(n).padStart(12, "0")}`;

lines.push("-- Homework (submissions cascade on delete)");
lines.push(
  `delete from public.homework where id in (${HOMEWORK_SEED.map((_, i) =>
    q(hwUuid(i + 1))
  ).join(", ")});`
);
HOMEWORK_SEED.forEach((h, i) => {
  lines.push(
    `insert into public.homework (id, group_name, title, description, section, due_date) values\n  (${q(
      hwUuid(i + 1)
    )}, ${q(h.groupName)}, ${q(h.title)}, ${q(h.description)}, ${q(
      h.section
    )}, ${q(h.dueDate)});`
  );
});
lines.push("");

// --- Vocabulary ------------------------------------------------------------
// Teacher lists go to the whole group; saved-while-reading words belong to the
// demo student, so both sources show up in the UI.
const g62 = STUDENTS.map((s, i) => ({ ...s, uuid: studentUuid(i) })).filter(
  (s) => s.group === "IELTS 62"
);
lines.push("-- Personal vocabulary (lib/vocabulary-data.ts)");
lines.push(
  `delete from public.vocabulary_entries where student_id in (${g62
    .map((s) => q(s.uuid))
    .join(", ")});`
);
g62.forEach((student) => {
  DEMO_VOCABULARY.filter(
    (w) => w.source === "teacher" || student.uuid === studentUuid(0)
  ).forEach((w) => {
    lines.push(
      `insert into public.vocabulary_entries (center_id, student_id, term, phonetic, translation, example, source, topic, status) values\n  (${q(
        CENTER_ID
      )}, ${q(student.uuid)}, ${q(w.term)}, ${w.phonetic ? q(w.phonetic) : "null"}, ${q(
        w.translation
      )}, ${w.example ? q(w.example) : "null"}, ${q(w.source)}, ${
        w.topic ? q(w.topic) : "null"
      }, ${q(w.status ?? "new")});`
    );
  });
});
lines.push("");

lines.push("-- Work awaiting review; ages are relative to when this is applied");
PENDING_REVIEW_SEED.forEach((p) => {
  const studentIndex = STUDENTS.findIndex((s) => s.name === p.studentName);
  const hwIndex = HOMEWORK_SEED.findIndex((h) => h.id === p.homeworkId);
  if (studentIndex === -1 || hwIndex === -1) return;
  lines.push(
    `insert into public.homework_submissions (homework_id, student_id, content, status, submitted_at) values\n  (${q(
      hwUuid(hwIndex + 1)
    )}, ${q(studentUuid(studentIndex))}, ${q(
      "Работа отправлена на проверку."
    )}, 'submitted', now() - interval '${p.hoursAgo} hours');`
  );
});
lines.push("");

process.stdout.write(lines.join("\n"));
