/**
 * Rebuilds supabase/setup.sql — the one-shot "paste into the SQL Editor" file.
 *
 * It is a plain concatenation of every migration (in numeric order) followed by
 * the seed files. Regenerate it after adding a migration or changing a seed,
 * otherwise setup.sql silently drifts from the migrations it is meant to mirror.
 *
 *   node scripts/gen-setup.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from "fs";
import { join } from "path";

const root = new URL("..", import.meta.url).pathname;
const migrationsDir = join(root, "supabase", "migrations");
const supabaseDir = join(root, "supabase");

const migrations = readdirSync(migrationsDir)
  .filter((f) => f.endsWith(".sql"))
  .sort();

// Order matters: schema first, then data.
const seeds = ["seed.sql", "cambridge-seed.sql", "groups-seed.sql"];

const parts = [
  "-- EduFlow — one-shot setup: schema + RLS + seed.",
  "-- Paste this whole file into the Supabase SQL Editor and Run.",
  "-- Safe to re-run (idempotent).",
  "--",
  "-- GENERATED by scripts/gen-setup.mjs — do not edit by hand.",
  `-- Sources: ${[...migrations, ...seeds].join(", ")}`,
  "",
];

for (const file of migrations) {
  parts.push(`-- ===== migrations/${file} =====`, "");
  parts.push(readFileSync(join(migrationsDir, file), "utf8").trim(), "");
}

for (const file of seeds) {
  parts.push(`-- ===== ${file} =====`, "");
  parts.push(readFileSync(join(supabaseDir, file), "utf8").trim(), "");
}

writeFileSync(join(supabaseDir, "setup.sql"), parts.join("\n") + "\n", "utf8");
console.log(
  `✓ setup.sql rebuilt from ${migrations.length} migrations + ${seeds.length} seeds`
);
